@startuml PlayerLogic
state "PlayerLogic State" as Vardag_PlayerLogic_State

Vardag_PlayerLogic_State --> Vardag_PlayerLogic_State : PhysicsTick
Vardag_PlayerLogic_State --> Vardag_PlayerLogic_State : RequestLook
Vardag_PlayerLogic_State --> Vardag_PlayerLogic_State : RequestMove

Vardag_PlayerLogic_State : OnPhysicsTick → Move, UpdateVelocity
Vardag_PlayerLogic_State : OnRequestLook → Look

[*] --> Vardag_PlayerLogic_State
@enduml