@startuml GameLogic
state "GameLogic State" as Vardag_GameLogic_State {
  state "Paused" as Vardag_GameLogic_State_Paused
  state "Playing" as Vardag_GameLogic_State_Playing
}

Vardag_GameLogic_State_Paused --> Vardag_GameLogic_State_Playing : OnPausePressed
Vardag_GameLogic_State_Playing --> Vardag_GameLogic_State_Paused : OnPausePressed

Vardag_GameLogic_State : OnGamePausedSync() → CaptureMouse, SetPauseMode
Vardag_GameLogic_State : OnGameQuitRequested() → QuitGame

[*] --> Vardag_GameLogic_State_Playing
@enduml